version: '3.7'

services:
  php:
    container_name: php
    build: ./.docker/infrastructure/${APP_ENV}/php
    volumes:
      - .:/var/www:cached
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8888:80
      - 8889:443
    volumes:
      - .:/var/www:cached
      - ./.docker/infrastructure/${APP_ENV}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/infrastructure/${APP_ENV}/nginx/certs/:/etc/nginx/certs/
    depends_on:
      - php

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/infrastructure/${APP_ENV}/db/data:/var/lib/mysql
      - ./.docker/infrastructure/${APP_ENV}/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/infrastructure/${APP_ENV}/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 8890:3306
